import fs from 'fs';
import path from 'path';
import test from 'tape';
import SimpleFreesound from '../server/SimpleFreesound';

/*
 * Define your own api key and download folder in <code>./constants.js</code>.
 * Their values will be used to instantiate the <code>SimpleFreesound</code>
 * class below;
 * <code>downloadsFolder</code> must be relative to <code>process.cwd()</code>.
 * <code>apiKey</code> is the value of the key generated by freesound when
 * creating a new application from your developer account.
 */
import { apiKey, downloadFolder } from './constants';

const cwd = process.cwd();
const absDownloadFolder = path.join(cwd, downloadFolder)

if (!fs.existsSync(absDownloadFolder))
  fs.mkdirSync(absDownloadFolder);

test('basic', (t) => {
  t.plan(1);

  const sf = new SimpleFreesound(apiKey, downloadFolder, '.');

  sf.query({
    search: [ 'abstract' ],
    duration: [ 0, 1 ],
    users: [ 'joseph.larralde' ],
  })
  .then(() => sf.download())
  .then(() => {
    sf.writeToFile('soundsInfo.json');
    t.equal(true, true, 'true is true');
  });
});
